const blogPosts = [
  {
    slug: 'techarena-2026-skandinaviens-storsta-tech',
    title: 'Techarena 2026 — Skandinaviens största tech- och affärsevent',
    date: '13 februari 2026',
    category: 'Events',
    excerpt: 'Temat var "New Era, Next Mindset" — en uppmaning att tänka storskaligt, innovativt och forma framtidens utveckling.',
    content: [
      { type: 'p', text: 'Temat för evenemanget var "New Era, Next Mindset" — en uppmaning att tänka storskaligt, tänka innovativt och forma framtidens utveckling under en period av snabb teknologisk utveckling.' },
      { type: 'p', text: 'Eventet lockade många deltagare och presenterade intressanta föreläsare från olika delar av världen, inklusive grundare, investerare, företagsledare och beslutsfattare inom teknik, entreprenörskap och investeringar.' },
      { type: 'quote', text: 'Dagarna gick för fort och jag önskar att det var fler dagar för att hinna med allt 😅' },
      { type: 'h3', text: 'Arenans komponenter' },
      { type: 'ul', items: [
        'Inspirerande keynotes och panelsamtal om AI, innovation, hållbarhet, ledarskap och framtidens affärsmodeller',
        'Workshops, diskussioner och roundtables med nätverksmöjligheter och idéutbyte',
        'Omfattande matchmaking-sessioner för en-på-en-möten mellan deltagare',
      ]},
      { type: 'p', text: 'Eventet presenterade prominenta branschföreträdare, politiker, Josef Fares och Zlatan Ibrahimović.' },
      { type: 'quote', text: 'Vilken energi och stämning! Jag är så tacksam för upplevelsen och möjligheten.' },
      { type: 'p', text: 'Techarena fungerade som en plattform för att utveckla framtidens tech- och affärsekosystem genom högkvalitativt innehåll och ett engagerat nätverk som fostrade idéer och samarbeten.' },
      { type: 'p', text: 'Jag ser fram emot kommande vecka med nya möten och möjligheter. Tack Techarena för erfarenheten!' },
    ],
  },
  {
    slug: 'ai-ordlista',
    title: 'AI ordlista 🧠',
    date: '2 februari 2026',
    category: 'AI',
    excerpt: 'AI-terminologi kan verka förvirrande. Här är 16 centrala begrepp som hjälper dig förstå AI-världen.',
    content: [
      { type: 'p', text: 'AI-terminologi kan verka förvirrande — lite som när nya slanguttryck dyker upp. Här presenterar jag 16 centrala begrepp inom AI-området.' },
      { type: 'dl', items: [
        { term: 'AI (Artificiell intelligens)', def: 'Datorer som kan göra saker som normalt kräver mänskligt tänkande, t.ex. förstå språk eller känna igen bilder.' },
        { term: 'Algoritm', def: 'Ett recept eller en instruktion som talar om för datorn vad den ska göra.' },
        { term: 'Maskininlärning', def: 'När en dator lär sig av exempel istället för att bli programmerad steg för steg.' },
        { term: 'Data', def: 'Information som AI tränas på, t.ex. text, bilder eller siffror.' },
        { term: 'Modell', def: 'Den färdiga AI:n efter att den tränats på data.' },
        { term: 'Träning', def: 'Processen där AI lär sig genom att analysera stora mängder data.' },
        { term: 'Prompt', def: 'Det du skriver eller säger till AI:n (din fråga eller instruktion).' },
        { term: 'Generativ AI', def: 'AI som kan skapa nytt innehåll, som text, bilder eller musik.' },
        { term: 'Språkmodell', def: 'En AI som är specialiserad på att förstå och skriva text.' },
        { term: 'Hallucination', def: 'När AI ger ett svar som låter övertygande men är fel eller påhittat.' },
        { term: 'Bias (snedvridning)', def: 'När AI ger orättvisa eller skeva svar på grund av ensidig data.' },
        { term: 'Automatisering', def: 'När AI tar över uppgifter som människor tidigare gjorde.' },
        { term: 'Deepfake', def: 'AI-skapad video, bild eller ljud som ser äkta ut men inte är det.' },
        { term: 'Integritet', def: 'Hur personuppgifter samlas in och skyddas när AI används.' },
        { term: 'Etisk AI', def: 'Att använda AI på ett ansvarsfullt, rättvist och säkert sätt.' },
        { term: 'Chattbot', def: 'Ett AI-program som man kan prata med via text eller tal.' },
      ]},
      { type: 'p', text: 'Vill du prata om din organisations AI-strategi? Hör av dig!' },
    ],
  },
  {
    slug: 'vad-ar-skillnaderna',
    title: 'Vad är skillnaderna?',
    date: '29 januari 2026',
    category: 'Tips',
    excerpt: 'Ibland är det inte så lätt att veta vad som är vad. Här är en förenklad bild av skillnaderna mellan Copilot gratis- och betalversion.',
    content: [
      { type: 'p', text: 'Ibland är det inte så lätt att veta vad som är vad.' },
      { type: 'p', text: 'Här ser du en förenklad samlad bild på vad skillnaderna är på Copilot gratis- och betalversion.' },
      { type: 'h3', text: 'Copilot (gratis)' },
      { type: 'ul', items: [
        'Tillgång till grundläggande AI-chatt',
        'Begränsade funktioner i Microsoft 365-appar',
        'Ingen integration med företagsdata',
        'Bra för enklare frågor och uppgifter',
      ]},
      { type: 'h3', text: 'Copilot för Microsoft 365 (betald)' },
      { type: 'ul', items: [
        'Full integration med Word, Excel, PowerPoint, Outlook och Teams',
        'Tillgång till företagsdata via Microsoft Graph',
        'Avancerade funktioner som mötessammanfattningar och e-postförslag',
        'Anpassad efter organisationens behov och data',
      ]},
      { type: 'p', text: 'Vill du veta mer om vilken version som passar din organisation? Kontakta mig så pratar vi igenom det.' },
    ],
  },
  {
    slug: '2026-dags-for-en-omstart',
    title: '2026 — dags för en omstart?',
    date: '13 januari 2026',
    category: 'Strategi',
    excerpt: '2025 slutade med Årets Awards och en AI-strateg-certifiering. Nu blickar vi framåt mot 2026!',
    content: [
      { type: 'p', text: '2025 slutade med en positiv överraskning — Modern 365 Consulting fick Årets Awards! Det är en otrolig framgång och stolthet som jag delar med mig av detta. Jag är tacksam för denna utmärkelse och ser fram emot att fortsätta utveckla mitt bolag.' },
      { type: 'p', text: 'Och nu är det 2026! Vad ska jag hitta på då?' },
      { type: 'p', text: '2025 blev jag också certifierad AI-strateg. Det händer enormt mycket inom det området och det går fort och det är svårt att hänga med. Därför vill jag finnas till och hjälpa företag som vill förstå sig på AI och hur det kan hjälpa verksamheten på bästa sätt så att det ger affärsvärde.' },
      { type: 'p', text: 'I år ser jag fram emot att få jobba mycket med AI-strategier, Copilot, agenter och annat skoj. Häng med på resan!' },
    ],
  },
  {
    slug: 'mina-microsoft-ignite-spaningar',
    title: 'Mina Microsoft Ignite spaningar 👀',
    date: '18 november 2025',
    category: 'Events',
    excerpt: 'Att följa Microsofts utveckling är som att gå in i en godisbutik med 1000 olika sorter. Här är mina utvalda sessioner.',
    content: [
      { type: 'p', text: 'Att följa Microsofts utveckling är som att gå in i en godisbutik med 1000 olika sorter. Man blir helt överväldigad av alla alternativ och det är svårt att välja.' },
      { type: 'h3', text: 'Mina utvalda sessioner' },
      { type: 'ul', items: [
        'Opening Keynote — sätter tonen för veckan',
        'Grow your business with Microsoft AI Cloud Partner program — anpassat till Modern 365 Consultings utveckling',
        'Innovate with Low-Code AI and Agents — fokuserat på utveckling',
        'Drive Copilot adoption with strategies that scale — relevant för kommande AI-strateg-diplom',
        'M365 Copilot Agents: Powering retail & consumer goods partner success — intressanta affärsfall',
      ]},
      { type: 'p', text: 'Jag lovar att dela utvärderingar av sessionerna senare. Vilken spännande vecka! 🔥' },
    ],
  },
  {
    slug: 'microsoft-ignite-2025-ai-eran-tar-fart',
    title: 'Microsoft Ignite 2025 — AI-eran tar fart 🔥',
    date: '17 november 2025',
    category: 'Nyheter',
    excerpt: 'Tusentals IT-proffs, utvecklare och företagsledare samlades på Moscone Center i San Francisco.',
    content: [
      { type: 'p', text: 'Microsoft Ignite 2025, 18–21 november på Moscone Center i San Francisco. Tusentals IT-proffs, utvecklare och företagsledare samlades för årets stora Microsoft-konferens med fokus på AI, molninnovation, säkerhet och samarbete i Microsoft 365.' },
      { type: 'p', text: 'Vi befinner oss mitt i en ny era av AI-driven innovation. Många företag måste nu gå från att testa till att implementera AI-lösningar.' },
      { type: 'p', text: 'Jag finns tillgänglig i januari för AI-strategikonsultationer. Vill du boka tid? Hör av dig till nathalie.tornbrant@m365consulting.se.' },
      { type: 'p', text: 'Börja 2026 med en plan!' },
    ],
  },
]

export default blogPosts
